apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: mcander/hipster-front-shit:latest
    name: frontend
    env:
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "localhost:3550"
    - name: CURRENCY_SERVICE_ADDR
      value: "localhost:7000"
    - name: CART_SERVICE_ADDR
      value: "localhost:7070"
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "localhost:8080"
    - name: SHIPPING_SERVICE_ADDR
      value: "localhost:50051"
    - name: CHECKOUT_SERVICE_ADDR
      value: "localhost:5050"
    - name: AD_SERVICE_ADDR
      value: "localhost:9555"
  restartPolicy: Never
